### ISSUE TITLE
COVIDSenti Dataset

### ISSUE THREAD

**Issue by datavistics** [usmaann/COVIDSenti#1]
@usmaann , do you plan on providing the data for COVIDSenti that corresponds to your recent [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9340540)?

Thanks!

**Comment by usmaann** [comment]
Data is uploaded. 

Sorry for the late response. I was extremely busy with one of the submission.

**Comment by datavistics** [comment]
Thanks so much!
